version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass supersecretpassword
    environment:
      - REDIS_PASSWORD=supersecretpassword
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB="postgresdb"
    restart: always

volumes:
  redis_data:
  postgres_data:
