version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass supersecretpassword
    environment:
      - REDIS_PASSWORD=supersecretpassword
    restart: always

volumes:
  redis_data:
  postgres_data:
