import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { Footer } from "@/components/globals/footer";
import { Navbar } from "@/components/globals/navbar";
import TanStackProvider from "@/provider/tanstack";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <TanStackProvider>
            <Navbar />
            {children}
            <Toaster />
            <Footer />
          </TanStackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
